apiVersion: monitoring.operator.ibm.com/v1alpha1
kind: PrometheusExt
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  name: ibm-monitoring
spec:
    storageClassName: ""
    grafanaSvcName: "ibm-monitoring-grafana"
    grafanaSvcPort: 3000
    clusterPort: 443
    prometheusConfig:
      serviceAccount: ibm-monitoring-prometheusext-operand
      retention: 24h
      servicePort: 9090
      nodeMemoryThreshold: 85
      nodeCPUThreshold: 85
      logLevel: info
    alertManagerConfig:
      serviceAccount: ibm-monitoring-prometheusext-operand
      servicePort: 9093
      logLevel: info
    mcmMonitor:
      isHubCluster: false
      serviceAccount: ibm-monitoring-mcm-ctl
    certs:
      monitoringSecret: ibm-monitoring-certs
      monitoringClientSecret: ibm-monitoring-client-certs
      issuer: cs-ca-clusterissuer
      autoClean: true
    iamProvider:
      idProviderSvc: platform-identity-provider
      idProviderSvcPort: 4300
      idManagementSvc: platform-identity-management
      idManagementSvcPort: 4500
    prometheusOperator: {}

        
