apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
  name: ibm-monitoring-prometheus-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: common-monitoring
        app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
        name: ibm-monitoring-prometheus-operator-ext
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
          command:
            - ibm-monitoring-prometheusext-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheusext-operator"
            - name: AM_IMAGE
              value: quay.io/opencloudio/alertmanager@sha256:3b7d78681b1163c655a7fee480af80b926ebd30a702dcbc8845b88a7cd00a9c7
            - name: PROME_IMAGE
              value: quay.io/opencloudio/prometheus@sha256:64b44a34a7ffb46d6d7a3a3a3e9e5b2648688bab87db40acf1b3fe28efc44df9
            - name: CM_RELOAD_IMAGE
              value: quay.io/opencloudio/configmap-reload@sha256:39046dda4ac90fb17674ab52292b9d3a214f5b3e2d01831c39b23e19fbe3cd95
            - name: PROM_OP_IMAGE
              value: quay.io/opencloudio/prometheus-operator@sha256:97c5647038f5ebc5c5923ef20e61cdf51a3321d7360000ad3b78fb6a38b2daf7
            - name: PROM_CONF_IMAGE
              value: quay.io/opencloudio/prometheus-config-reloader@sha256:6d76da1fe18ac9c343dbd104d2763e2918c9ed89b7dac659907286eda9fe0e94
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:fedfb66a2c552d6bf1a741dbe42b74aaf0775f8a0618b1f39815474ebc811b7b
            - name: MCM_HELPER_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:c0820a378fe87f79e0d553e3ff0bc4dc3d2d3312b7b6ae0c788f9bfe8a632966
            - name: MCM_IMAGE
              value: quay.io/opencloudio/prometheus-controller@sha256:361762d741bfbb1359b6b0038328dae95f5debe70dc2813f394aa0270f1373e6