apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  name: ibm-monitoring-prometheus-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: common-monitoring
        app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
        name: ibm-monitoring-prometheus-operator-ext
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator:1.9.0
          command:
          - ibm-monitoring-prometheusext-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheusext-operator"
            - name: AM_IMAGE
              value: quay.io/opencloudio/alertmanager@sha256:4810de4093d11a0e5477ffc252e47561d36bbea57b288246a33d561e25495355
            - name: PROME_IMAGE
              value: quay.io/opencloudio/prometheus@sha256:4810de4093d11a0e5477ffc252e47561d36bbea57b288246a33d561e25495355
            - name: CM_RELOAD_IMAGE
              value: quay.io/opencloudio/configmap-reload@sha256:c55a9bac9ea08a6973dc89cd996352ab44207b677e255c005bf5b053273d7c31
            - name: PROM_OP_IMAGE
              value: quay.io/opencloudio/prometheus-operator@sha256:be2e8d45fc92c6b568ad2f1343e0d7bd705bacbbf1f9e7a0496675d236bf7f94
            - name: PROM_CONF_IMAGE
              value: quay.io/opencloudio/prometheus-config-reloader@sha256:90acf5396ae74474a9ada44487cfefd200a6319b315765fd631925b48320e3e4
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:c7f4960f2df024cd3b43b08d115047293359478b5b91b15e9f3b8c40a3af74d3
            - name: MCM_HELPER_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:d56a8bd8389757be3aa05a4026db5e33dada059d8e4112737d828a9440bdd7d7
            - name: MCM_IMAGE
              value: quay.io/opencloudio/prometheus-controller@sha256:83162c58b9abcea9b79eca0962835fa96c4b091a0ff4ba384279eaad5e2c5ed1
