apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
    operatorframework.io/arch.s390x: supported
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
  name: ibm-monitoring-prometheus-operator-ext
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-prometheus-operator-ext
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: common-monitoring
        app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
        name: ibm-monitoring-prometheus-operator-ext
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-prometheus-operator-ext
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: ibm-monitoring-prometheus-operator-ext
          image: quay.io/opencloudio/ibm-monitoring-prometheusext-operator
          command:
            - ibm-monitoring-prometheusext-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-prometheusext-operator"
            - name: AM_IMAGE
              value: quay.io/opencloudio/alertmanager@sha256:117b757d57992ca420647943d20f9132db066cca69413b0f9026760cf078da68
            - name: PROME_IMAGE
              value: quay.io/opencloudio/prometheus@sha256:02d4f877a5e4496fc6f98c39bbb01540f1c4c3ca7d24275c3d5a16f2cadd0d8c
            - name: CM_RELOAD_IMAGE
              value: quay.io/opencloudio/configmap-reload@sha256:f2a1851c5defdbc834573b1c1a2402b4608d6432c62ba1372fe610b7a85b271c
            - name: PROM_OP_IMAGE
              value: quay.io/opencloudio/prometheus-operator@sha256:35a01d9bb51d43becc0983f53818590bef2d0a4e5cfde7b392eef390038f3ce6
            - name: PROM_CONF_IMAGE
              value: quay.io/opencloudio/prometheus-config-reloader@sha256:40cfae4583c7cb4f0a24e979edfa4a46c549b71fd97b4330db666a90e8d6c631
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:58fdc4b437827e8865ecd667f40a71dffdd056298b33b787a4da980928960a05
            - name: MCM_HELPER_IMAGE
              value: quay.io/opencloudio/icp-initcontainer@sha256:c0820a378fe87f79e0d553e3ff0bc4dc3d2d3312b7b6ae0c788f9bfe8a632966
            - name: MCM_IMAGE
              value: quay.io/opencloudio/prometheus-controller@sha256:630a91d98f77fc58113016577e4e659eb0fb1b716cee9a9e2558c8eed3d140d2
