apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  creationTimestamp: null
  name: ibm-monitoring-prometheus-operator-ext
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - alertmanagers
  - servicemonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  verbs:
  - '*'
- apiGroups:
  - certmanager.k8s.io
  resources:
  - clusterissuers
  verbs:
  - use
- apiGroups:
  - monitoring.operator.ibm.com
  resources:
  - prometheusexts
  - prometheusexts/finalizers
  - prometheusexts/status
  verbs:
  - '*'
- apiGroups:
  - monitoring.operator.ibm.com
  resources:
  - exporters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  creationTimestamp: null
  name: ibm-monitoring-mcm-ctl
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  - configmaps
  - secrets
  - pods
  - services/finalizers
  verbs:
  - '*'
- nonResourceURLs: ["/metrics"]
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheuses
  - alertmanagers
  - servicemonitors
  - prometheusrules
  - podmonitors
  - prometheuses/finalizers
  - alertmanagers/finalizers
  verbs:
  - '*'
- apiGroups:
  - "monitoringcontroller.cloud.ibm.com"
  resources:
  - monitoringdashboards
  verbs:
  - '*'
- apiGroups:
  - "mcm.ibm.com"
  resources:
  - clusterstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  creationTimestamp: null
  name: ibm-monitoring-prometheusext-operand
rules:
- apiGroups:
  - ""
  resources:
  - services
  - nodes
  - nodes/proxy
  - endpoints
  - pods
  - configmaps
  verbs:
  - get
  - list
  - watch
- nonResourceURLs: ["/metrics"]
  verbs:
  - get
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  creationTimestamp: null
  name: prometheus-k8s-role
rules:
- apiGroups:
  - ''
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: prometheusext
    app.kubernetes.io/managed-by: ibm-monitoring-prometheusext-operator
  creationTimestamp: null
  name: prometheus-operator-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - prometheuses
  - prometheuses/finalizers
  - alertmanagers/finalizers
  - servicemonitors
  - podmonitors
  - prometheusrules
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - delete
- apiGroups:
  - ''
  resources:
  - services
  - services/finalizers
  - endpoints
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - get


